// This file is a part of Music Turret project.
// 
// Copyright 2018 Emzi0767
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Security.Cryptography;

namespace Emzi0767.MusicTurret.Services
{
    /// <summary>
    /// Cryptographically-secure random number generator implementation, mostly compatible with <see cref="Random"/>.
    /// </summary>
    public sealed class CSPRNG : IDisposable
    {
        /// <summary>
        /// Gets whether the generator was already disposed.
        /// </summary>
        public bool IsDisposed { get; set; } = false;
        private RandomNumberGenerator RNG { get; } = RandomNumberGenerator.Create();

        /// <summary>
        /// Generates a specified number of bytes.
        /// </summary>
        /// <param name="count">Number of bytes to generate.</param>
        /// <returns>Generated bytes.</returns>
        public byte[] GetBytes(int count)
        {
            if (count <= 0)
                throw new ArgumentOutOfRangeException("Must get at least 1 byte.", nameof(count));

            var bts = new byte[count];
            this.RNG.GetBytes(bts);
            return bts;
        }

        /// <summary>
        /// Generates a specified number of bytes.
        /// </summary>
        /// <param name="count">Number of bytes to generate.</param>
        /// <param name="bytes">Generated bytes.</param>
        public void GetBytes(int count, out byte[] bytes)
        {
            if (count <= 0)
                throw new ArgumentOutOfRangeException("Must get at least 1 byte.", nameof(count));

            bytes = new byte[count];
            this.RNG.GetBytes(bytes);
        }

        /// <summary>
        /// Generates an unsigned 8-bit integer.
        /// </summary>
        /// <returns>A random unsigned 8-bit integer.</returns>
        public byte GetU8()
            => this.GetBytes(1)[0];

        /// <summary>
        /// Generates a signed 8-bit integer.
        /// </summary>
        /// <returns>A random signed 8-bit integer.</returns>
        public sbyte GetS8()
            => (sbyte)this.GetBytes(1)[0];

        /// <summary>
        /// Generates an unsigned 16-bit integer.
        /// </summary>
        /// <returns>A random unsigned 16-bit integer.</returns>
        public ushort GetU16()
            => BitConverter.ToUInt16(this.GetBytes(2), 0);

        /// <summary>
        /// Generates a signed 16-bit integer.
        /// </summary>
        /// <returns>A random signed 16-bit integer.</returns>
        public short GetS16()
            => BitConverter.ToInt16(this.GetBytes(2), 0);

        /// <summary>
        /// Generates an unsigned 32-bit integer.
        /// </summary>
        /// <returns>A random unsigned 32-bit integer.</returns>
        public uint GetU32()
            => BitConverter.ToUInt32(this.GetBytes(4), 0);

        /// <summary>
        /// Generates a signed 32-bit integer.
        /// </summary>
        /// <returns>A random signed 32-bit integer.</returns>
        public int GetS32()
            => BitConverter.ToInt32(this.GetBytes(4), 0);

        /// <summary>
        /// Generates an unsigned 32-bit integer.
        /// </summary>
        /// <returns>A random unsigned 32-bit integer.</returns>
        public ulong GetU64()
            => BitConverter.ToUInt64(this.GetBytes(8), 0);

        /// <summary>
        /// Generates a signed 64-bit integer.
        /// </summary>
        /// <returns>A random signed 64-bit integer.</returns>
        public long GetS64()
            => BitConverter.ToInt64(this.GetBytes(8), 0);

        /// <summary>
        /// Generates a random 32-bit signed integer between 0 and <see cref="int.MaxValue"/>.
        /// </summary>
        /// <returns>Generated 32-bit signed integer.</returns>
        public int Next()
            => this.Next(0, int.MaxValue);

        /// <summary>
        /// Generates a random 32-bit signed integer between 0 and <paramref name="max"/>.
        /// </summary>
        /// <param name="max">Maximum value to generate. Needs to be greater than 0.</param>
        /// <returns>Generated 32-bit signed integer.</returns>
        public int Next(int max)
            => this.Next(0, max);

        /// <summary>
        /// Generates a random 32-bit signed integer between <paramref name="min"/> and <paramref name="max"/>.
        /// </summary>
        /// <param name="min">Minimum value to generate.</param>
        /// <param name="max">Maximum value to generate. Must be greater than <paramref name="min"/>.</param>
        /// <returns>Generated 32-bit signed integer.</returns>
        public int Next(int min, int max)
        {
            if (max <= min)
                throw new ArgumentException("Maximum needs to be greater than minimum.", nameof(max));

            var offset = 0;
            if (min < 0)
                offset = -min;

            min += offset;
            max += offset;

            return Math.Abs(this.GetS32()) % (max - min) + min - offset;
        }

        /// <summary>
        /// Generates a random 32-bit IEEE 754 floating-point number between 0.0 and 1.0 inclusive.
        /// </summary>
        /// <returns>A random 32-bit IEEE 754 floating-point number.</returns>
        public float NextSingle()
        {
            var (l1, l2) = ((float)this.GetS32(), (float)this.GetS32());
            return Math.Abs(l1 / l2) % 1.0F;
        }

        /// <summary>
        /// Generates a random 64-bit IEEE 754 floating-point number between 0.0 and 1.0 inclusive.
        /// </summary>
        /// <returns>A random 64-bit IEEE 754 floating-point number.</returns>
        public double NextDouble()
        {
            var (l1, l2) = ((double)this.GetS64(), (double)this.GetS64());
            return Math.Abs(l1 / l2) % 1.0;
        }

        /// <summary>
        /// Disposes this random number generator.
        /// </summary>
        public void Dispose()
        {
            if (this.IsDisposed)
                throw new ObjectDisposedException("This random number generator is already disposed.");

            this.IsDisposed = true;
            this.RNG.Dispose();
        }
    }
}
